apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-c8g1
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0075-tenant/tkwch-fix-0075-0075-app/devfile-sample-c8g1@sha256:49cfe5d6a640f720d3fcae36236799d9764970877e55aade4170517ba811cbf5
        name: my-nodejs
        resources: {}
status: {}
